osx_image: xcode7.3
language: objective-c
xcode_project: DemoAnimations.xcodeproj
xcode_scheme: Animations

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update --platform iOS
