osx_image: xcode7.3
language: objective-c
xcode_project: DemoAnimations.xcodeproj
xcode_scheme: Animations
target: DemoAnimations

script:
  - xcodebuild -project {xcode_project}.xcodeproj -target {target} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update --platform iOS
